services:
  backend:
    build: ./backend
    container_name: insta-backend
    ports:
      - "9000:3000"
    restart: always
    volumes:
      - ./backend/uploads:/usr/src/app/uploads

  frontend:
    build: ./frontend
    container_name: insta-frontend
    ports:
      - '3000:5173'
 